BEGIN TRY TRUNCATE TABLE dbo.STAGING_Coffee END TRY BEGIN CATCH END CATCH
INSERT INTO dbo.STAGING_Coffee
(
	 ID
	,Species
	,Owner
	,CountryOfOrigin
	,FarmName
	,LotNumber
	,Mill
	,ICONumber
	,Company
	,Altitude
	,Region
	,Producer
	,NumberofBags
	,BagWeight
	,InCountryPartner
	,HarvestYear
	,GradingDate
	,Owner1
	,Variety
	,ProcessingMethod
	,Aroma
	,Flavor
	,Aftertaste
	,Acidity
	,Body
	,Balance
	,Uniformity
	,CleanCup
	,Sweetness
	,CupperPoints
	,TotalCupPoints
	,Moisture
	,CategoryOneDefects
	,Quakers
	,Color
	,CategoryTwoDefects
	,Expiration
	,CertificationBody
	,CertificationAddress
	,CertificationContact
	,UnitOfMeasurement
	,AltitudeLowMeters
	,AltitudeHighMeters
	,AltitudeMeanMeters
)
SELECT
	 Column_1
	,Species
	,Owner
	,Country_of_Origin
	,Farm_Name
	,Lot_Number
	,Mill
	,ICO_Number
	,Company
	,Altitude
	,Region
	,Producer
	,Number_of_Bags
	,Bag_Weight
	,In_Country_Partner
	,Harvest_Year
	,Grading_Date
	,Owner_1
	,Variety
	,Processing_Method
	,Aroma
	,Flavor
	,Aftertaste
	,Acidity
	,Body
	,Balance
	,Uniformity
	,Clean_Cup
	,Sweetness
	,Cupper_Points
	,Total_Cup_Points
	,Moisture
	,Category_One_Defects
	,Quakers
	,Color
	,Category_Two_Defects
	,Expiration
	,Certification_Body
	,Certification_Address
	,Certification_Contact
	,unit_of_measurement
	,altitude_low_meters
	,altitude_high_meters
	,altitude_mean_meters
FROM dbo.STAGING_Data_Arabica
ORDER BY
	 Species
	,Column_1

INSERT INTO dbo.STAGING_Coffee
(
	 ID
	,Species
	,Owner
	,CountryOfOrigin
	,FarmName
	,LotNumber
	,Mill
	,ICONumber
	,Company
	,Altitude
	,Region
	,Producer
	,NumberofBags
	,BagWeight
	,InCountryPartner
	,HarvestYear
	,GradingDate
	,Owner1
	,Variety
	,ProcessingMethod
	,Aroma
	,Flavor
	,Aftertaste
	,Acidity
	,Body
	,Balance
	,Uniformity
	,CleanCup
	,Sweetness
	,CupperPoints
	,TotalCupPoints
	,Moisture
	,CategoryOneDefects
	,Quakers
	,Color
	,CategoryTwoDefects
	,Expiration
	,CertificationBody
	,CertificationAddress
	,CertificationContact
	,UnitOfMeasurement
	,AltitudeLowMeters
	,AltitudeHighMeters
	,AltitudeMeanMeters
)
SELECT
	 Column_1
	,Species
	,Owner
	,Country_of_Origin
	,Farm_Name
	,Lot_Number
	,Mill
	,ICO_Number
	,Company
	,Altitude
	,Region
	,Producer
	,Number_of_Bags
	,Bag_Weight
	,In_Country_Partner
	,Harvest_Year
	,Grading_Date
	,Owner_1
	,Variety
	,Processing_Method
	,Fragrance_Aroma
	,Flavor
	,Aftertaste
	,Salt_Acid
	,Mouthfeel
	,Balance
	,Uniform_Cup
	,Clean_Cup
	,Bitter_Sweet
	,Cupper_Points
	,Total_Cup_Points
	,Moisture
	,Category_One_Defects
	,Quakers
	,Color
	,Category_Two_Defects
	,Expiration
	,Certification_Body
	,Certification_Address
	,Certification_Contact
	,unit_of_measurement
	,altitude_low_meters
	,altitude_high_meters
	,altitude_mean_meters
FROM dbo.STAGING_Data_Robusta
ORDER BY
	 Species
	,Column_1
GO
